[package]
name = "matrix_operations"
version = "0.1.0"
authors = ["Torgeir Brenn <torgeir.brenn@gmail.com>"]
edition = "2021"

[lib]
name = "matrix_operations"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.19.1"
features = ["extension-module"]